# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Build Extension

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      max-parallel: 3
      matrix:
        ghidra:
          - "11.4.2"
          - "11.4.1"
          - "11.4"
          - "11.3.2"
          - "11.3.1"
          - "11.3"
          - "11.2.1"
          - "11.2"
    steps:
    - name: Checkout
      uses: actions/checkout@v5

    - name: Setup JDK
      uses: actions/setup-java@v5
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Setup Ghidra
      uses: antoniovazquezblanco/setup-ghidra@v2.0.12
      with:
        version: ${{ matrix.ghidra }}

    # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
    # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@017a9effdb900e5b5b2fddfb590a105619dca3c3 # v4.4.2
      with:
        gradle-version: '8.5'

    - name: Build with Gradle Wrapper
      run: gradle buildExtension
      working-directory: ./R4Ghidra

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: GolangAnalyzerExtension_Ghidra_${{ matrix.ghidra }}
        path: GolangAnalyzerExtension/dist/*.zip

  release:
    runs-on: "ubuntu-latest"
    needs: [build]

    steps:
    - name: Download binaries
      uses: actions/download-artifact@v5

    - name: Release 
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          R4Ghidra_Ghidra_*/*.zip
          R4Ghidra-javadoc/*.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
